// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderFoodOnlineMicroservices.Services.ProductAPI.Data;

#nullable disable

namespace OrderFoodOnlineMicroservices.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240321152815_Create_ProductsTbl_SeedData")]
    partial class Create_ProductsTbl_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderFoodOnlineMicroservices.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Crispy fish served with hot chips, a classic dish loved by many.<br/> Perfect for a satisfying meal.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Fish and Chips",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "A hearty dish with minced meat and mashed potatoes on top.<br/> Comfort food at its best.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Shepherd's Pie",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "A delicious pie filled with sweet apples and cinnamon.<br/> Perfect for dessert lovers.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Apple Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Tender slices of roast beef served with gravy and vegetables.<br/> A classic entree choice.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Roast Beef",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
